### PR TITLE
Qt project

### LINKED ISSUE #16: Prepare CMake for Qt

### LINKED ISSUE #19: Prepare Qt application base

### PR DESCRIPTION
**Pull request by TheTryton**
Added example Qt project with cmake

### CODE REVIEW

**Comment by grzanka** [comment]
@TheTryton can you rebase this to newest master ? In this way we could have this PR tested properly by github actions

**Comment by grzanka** [comment]
Over 2 hours of installing qt ?
image

**Review by grzanka — APPROVED** [review]
Looks OK

**Review by pawek001 — APPROVED** [review]
Looks OK

**Review by kdbogusz — APPROVED** [review]
Looks good to me

**Pull request merged**
